
package pt.axians.loan.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2021-06-02T17:20:55.775+01:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "AuthorizationFault", targetNamespace = "http://ws.loan.axians.pt/")
public class AuthorizationFault extends Exception {
    
    private java.lang.String authorizationFault;

    public AuthorizationFault() {
        super();
    }
    
    public AuthorizationFault(String message) {
        super(message);
    }
    
    public AuthorizationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthorizationFault(String message, java.lang.String authorizationFault) {
        super(message);
        this.authorizationFault = authorizationFault;
    }

    public AuthorizationFault(String message, java.lang.String authorizationFault, Throwable cause) {
        super(message, cause);
        this.authorizationFault = authorizationFault;
    }

    public java.lang.String getFaultInfo() {
        return this.authorizationFault;
    }
}
