package pt.axians.loan.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2021-06-02T17:20:55.795+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ws.loan.axians.pt/", name = "LoanWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanWS {

    @WebMethod
    @Action(input = "http://ws.loan.axians.pt/LoanWS/emprestimoRequestRequest", output = "http://ws.loan.axians.pt/LoanWS/emprestimoRequestResponse", fault = {@FaultAction(className = AuthorizationFault.class, value = "http://ws.loan.axians.pt/LoanWS/emprestimoRequest/Fault/AuthorizationException")})
    @WebResult(name = "emprestimoRequestResponse", targetNamespace = "http://ws.loan.axians.pt/", partName = "result")
    public EmprestimoRequestResponse emprestimoRequest(
        @WebParam(partName = "parameters", name = "emprestimoRequest", targetNamespace = "http://ws.loan.axians.pt/")
        EmprestimoRequest parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.loan.axians.pt/", header = true)
        Token token
    ) throws AuthorizationFault;
}
