
package pt.axians.loan.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoanWSService", targetNamespace = "http://ws.loan.axians.pt/", wsdlLocation = "http://localhost:8084/loan?wsdl")
public class LoanWSService
    extends Service
{

    private final static URL LOANWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOANWSSERVICE_EXCEPTION;
    private final static QName LOANWSSERVICE_QNAME = new QName("http://ws.loan.axians.pt/", "LoanWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/loan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOANWSSERVICE_WSDL_LOCATION = url;
        LOANWSSERVICE_EXCEPTION = e;
    }

    public LoanWSService() {
        super(__getWsdlLocation(), LOANWSSERVICE_QNAME);
    }

    public LoanWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOANWSSERVICE_QNAME, features);
    }

    public LoanWSService(URL wsdlLocation) {
        super(wsdlLocation, LOANWSSERVICE_QNAME);
    }

    public LoanWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOANWSSERVICE_QNAME, features);
    }

    public LoanWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoanWS
     */
    @WebEndpoint(name = "LoanWSPort")
    public LoanWS getLoanWSPort() {
        return super.getPort(new QName("http://ws.loan.axians.pt/", "LoanWSPort"), LoanWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanWS
     */
    @WebEndpoint(name = "LoanWSPort")
    public LoanWS getLoanWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.loan.axians.pt/", "LoanWSPort"), LoanWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOANWSSERVICE_EXCEPTION!= null) {
            throw LOANWSSERVICE_EXCEPTION;
        }
        return LOANWSSERVICE_WSDL_LOCATION;
    }

}
