
package pt.axians.loan.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoanWS", targetNamespace = "http://ws.loan.axians.pt/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanWS {


    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns pt.axians.loan.client.LoanRequestResponse
     * @throws AuthorizationFault
     */
    @WebMethod
    @WebResult(name = "loanRequestResponse", targetNamespace = "http://ws.loan.axians.pt/", partName = "result")
    @Action(input = "http://ws.loan.axians.pt/LoanWS/loanRequestRequest", output = "http://ws.loan.axians.pt/LoanWS/loanRequestResponse", fault = {
        @FaultAction(className = AuthorizationFault.class, value = "http://ws.loan.axians.pt/LoanWS/loanRequest/Fault/AuthorizationException")
    })
    public LoanRequestResponse loanRequest(
        @WebParam(name = "loanRequest", targetNamespace = "http://ws.loan.axians.pt/", partName = "parameters")
        LoanRequest parameters,
        @WebParam(name = "token", targetNamespace = "http://ws.loan.axians.pt/", header = true, partName = "token")
        Token token)
        throws AuthorizationFault
    ;

}
